name: Daily Benchmark

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ main, master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    
    - name: Run benchmark
      run: |
        devenv shell benchmark
    
    - name: Commit results
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Add benchmark results if they exist
        git add README.md || true
        git add snix-flamegraph.svg || true
        git add benchmark-results.md || true
        git add benchmark-results.json || true
        
        # Commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update benchmark results [skip ci]
          
          Automated benchmark run at $(date -u +%Y-%m-%d)"
          git push
        fi
    
    - name: Create issue if benchmark fails
      if: failure()
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Daily benchmark failed',
            body: `The daily benchmark workflow failed on ${new Date().toISOString()}.
            
            See the failed run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
          })
